name: dsp_base
description: "Firebase (Analytics, Crashlytics, App Check, Remote Config) and AdMob ads for ASC apps."
version: 2.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  android_id: ^0.5.1
  crypto: ^3.0.3
  device_info_plus: ^13.2.0
  firebase_analytics: ^12.0.1
  firebase_app_check: ^0.4.1+2
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.1
  firebase_remote_config: ^6.1.0
  flutter:
    sdk: flutter
  google_mobile_ads: ^9.1.0
  get: ^4.7.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
